name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up JDK 21
      uses: actions/setup-java@main
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle (Debug)
      run: ./gradlew app:assembleDebug

    - name: Rename debug APK
      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/NoStorageRestrict.apk

    - name: Upload debug APK
      uses: actions/upload-artifact@main
      with:
        name: NoStorageRestrict.apk
        path: app/build/outputs/apk/debug/NoStorageRestrict.apk

    - name: Collect debug APK
      uses: actions/download-artifact@main
      with:
        name: NoStorageRestrict.apk
